import { EncryptionProvider } from '../Encryption/EncryptionProvider';
import { DatabaseProvider } from '../Database/DatabaseProvider';
import { AuthProvider } from '../Auth/AuthProvider';
import { ConfigProvider } from '../Config/ConfigProvider';
import { FunctionProvider } from '../Support/FunctionProvider';
import { PaginateProvider } from '../Paginate/PaginateProvider';
import { RedisProvider } from '../Redis/RedisProvider';
import { ValidatorProvider } from '../Validation/ValidatorProvider';
declare const providers: (typeof EncryptionProvider | typeof DatabaseProvider | typeof AuthProvider | typeof ConfigProvider | typeof FunctionProvider | typeof PaginateProvider | typeof RedisProvider | typeof ValidatorProvider)[];
export { providers };
